# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parsed_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('page', models.IntegerField()),
                ('cacheLink', models.TextField()),
                ('altText', models.TextField(blank=True)),
            ],
        ),
    ]
