# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 12:00
from __future__ import unicode_literals

import accTool.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accTool', '0004_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='upload/pdf/', validators=[accTool.validators.validate_file_extension]),
        ),
    ]
