# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accTool', '0005_auto_20151213_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsed_image',
            name='count',
        ),
        migrations.RemoveField(
            model_name='parsed_image',
            name='page',
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='upload/pdf/'),
        ),
    ]
