# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accTool', '0007_auto_20151214_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
