# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accTool', '0009_headings'),
    ]

    operations = [
        migrations.AddField(
            model_name='headings',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
