# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accTool', '0010_headings_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('value', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
