# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accTool', '0011_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='key',
            new_name='k',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='value',
            new_name='v',
        ),
    ]
